fix: ajustes na configuração do dockerfile

diff --git a/frontend/docker/Dockerfile-prd b/frontend/docker/Dockerfile-prd
--- a/frontend/docker/Dockerfile-prd
+++ b/frontend/docker/Dockerfile-prd
@@ -8,8 +8,16 @@ WORKDIR /app
 # Install dependencies based on the preferred package manager
 COPY . ./
 
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
 RUN npm install
+
+RUN npm run build
 
 EXPOSE 3000
 
